# See the documentation for all configuration options https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: "chore(deps): "

  # things that only get run locally
  - package-ecosystem: 'npm'
    directory: '/dev/oidc-provider'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: "chore(deps): "
  - package-ecosystem: 'npm'
    directory: '/dev/script/generate-config'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: "chore(deps): "
  - package-ecosystem: 'npm'
    directory: '/scripts/sample-images'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: "chore(deps): "
  - package-ecosystem: 'npm'
    directory: '/scripts/reindex-images'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: "chore(deps): "


# Not scanning these projects for now as I'm not sure how noisy/annoying dependabot will be for the team.
#  # the frontend site
#  - package-ecosystem: 'npm'
#    directory: '/kahuna'
#    schedule:
#      interval: 'weekly'
#    commit-message:
#      prefix: "chore(deps): "
#
#  # things that run in an AWS Lambda environment
#  - package-ecosystem: 'npm'
#    directory: '/reaper'
#    schedule:
#      interval: 'weekly'
#    commit-message:
#      prefix: "chore(deps): "
#  - package-ecosystem: 'npm'
#    directory: '/image-counter-lambda'
#    schedule:
#      interval: 'weekly'
#    commit-message:
#      prefix: "chore(deps): "
#  - package-ecosystem: 'npm'
#    directory: '/s3watcher/lambda'
#    schedule:
#      interval: 'weekly'
#    commit-message:
#      prefix: "chore(deps): "
#  - package-ecosystem: 'npm'
#    directory: '/s3watcher/scripts'
#    schedule:
#      interval: 'weekly'
#    commit-message:
#      prefix: "chore(deps): "
